#!/system/bin/sh

echo "176000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo "691200" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo "interactive" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
